### ISSUE TITLE
Tasks failure caused by: java.lang.NoSuchMethodError: guru.nidi.graphviz.model.MutableGraph.nodeAttrs()Lguru/nidi/graphviz/attribute/MutableAttributed

### ISSUE THREAD

**Issue by emartynov** [vanniktech/gradle-dependency-graph-generator-plugin#101]
Steps:
1. Add plugin to the project and configure
2. Run `generateDependencyGraph` task

See
```
Caused by: java.lang.NoSuchMethodError: guru.nidi.graphviz.model.MutableGraph.nodeAttrs()Lguru/nidi/graphviz/attribute/MutableAttributed;
        at com.vanniktech.dependency.graph.generator.DotGenerator.generateGraph(DotGenerator.kt:32)
        at com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorTask.run(DependencyGraphGeneratorTask.kt:18)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

**Comment by vanniktech** [comment]
Are you somehow overriding the graphviz version? Maybe we need to update the library

**Comment by vanniktech** [comment]
I'm trying to update the version in https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/tree/update-graphviz but I've raised a question: https://github.com/nidi3/graphviz-java/issues/126

**Comment by emartynov** [comment]
Sorry for the late reply. We don't specify this version at all. Let me check if it comes from some transitive deps.
