### ISSUE TITLE
Dot command didn't succeed

### ISSUE THREAD

**Issue by kirillzh** [vanniktech/gradle-dependency-graph-generator-plugin#102]
Getting this error when running the graph task:
```
Caused by: java.io.IOException: command '[/bin/sh, -c, dot -Tsvg /var/folders/wr/454hnjvd7bq1z5dzttmdg6rm0000gn/T/GraphvizJava/DotEngine5653640766655008278/dotfile.dot -ooutfile.svg]' didn't succeed
        at guru.nidi.graphviz.service.DefaultExecutor.execute(DefaultExecutor.java:57)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:45)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:54)
        at guru.nidi.graphviz.service.CommandRunner.exec(CommandRunner.java:49)
        at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.execute(GraphvizCmdLineEngine.java:83)
```

I tried latest release version `0.5.0` as well as snapshot version `0.6.0`. I tried running `dot` command manually and was getting permissions error, running it with `sudo` seemed to work 😕

**Comment by vanniktech** [comment]
Seems to be a problem in the library we're using https://github.com/nidi3/graphviz-java

I haven't updated to the last version in quite a while.
